- .github/workflows/build.yml
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- deployment/src/test/java/io/quarkiverse/helm/test/KubernetesFullTest.java
- deployment/src/test/java/io/quarkiverse/helm/test/KubernetesMinimalTest.java
- deployment/src/test/resources/application-k8s-full.properties
- docs/modules/ROOT/pages/includes/attributes.adoc
- pom.xml
Fix https://github.com/quarkiverse/quarkus-helm/issues/2
> Bump Quarkus to 2.8.0.CR1

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/30
> Delete the output Helm folder if exists

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmChartConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
Fix https://github.com/quarkiverse/quarkus-helm/issues/31
> Allow setting a custom output location via configuration

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- integration-tests/helm-kubernetes-minimal/src/test/java/io/quarkiverse/helm/tests/kubernetes/EndpointTest.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/39
> fix: issue when using helm and quarkus test

- .github/workflows/build.yml
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmChartConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- deployment/src/main/resources/NOTES.template.txt
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
- docs/modules/ROOT/pages/index.adoc
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
- integration-tests/helm-openshift-minimal/pom.xml
- integration-tests/helm-openshift-minimal/src/main/java/io/quarkiverse/helm/tests/openshift/Endpoint.java
- integration-tests/helm-openshift-minimal/src/test/java/io/quarkiverse/helm/tests/openshift/OpenShiftMinimalIT.java
- integration-tests/pom.xml
Fix https://github.com/quarkiverse/quarkus-helm/issues/48
Fix https://github.com/quarkiverse/quarkus-helm/issues/49
> Fix compatibility issue with Helm and OpenShift extensions

- .github/workflows/build.yml
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmChartConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
Fix https://github.com/quarkiverse/quarkus-helm/issues/61
> feat: allow configure the chart api version

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/77
> Fix deletion of output folder before starting

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
- docs/modules/ROOT/pages/index.adoc
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/80
> Fix format issue in documentation and add a validation step to prevent

- deployment/pom.xml
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmChartUploader.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmDependencyConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/ValueReferenceConfig.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
- pom.xml
Fix https://github.com/quarkiverse/quarkus-helm/issues/67 Fix https://github.com/quarkiverse/quarkus-helm/issues/56
> Bump Quarkus to 2.13.0.Final

- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- docs/modules/ROOT/pages/index.adoc
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-with-dependency/src/main/resources/application.properties
- integration-tests/helm-kubernetes-with-dependency/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesWithDependencyIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/93
> feat: fetch Helm dependencies before packaging

- .github/workflows/build.yml
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmRepository.java
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
Fix https://github.com/quarkiverse/quarkus-helm/issues/92
> [CI] Install the Super Heroes microservice using Quarkus Helm

- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- integration-tests/helm-kubernetes-full/src/main/helm/values.schema.json
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/71
> Add values.schema.json file

- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
Fix https://github.com/quarkiverse/quarkus-helm/issues/107
> Fix double quote issue with generated Helm templates

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmChartConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
- integration-tests/helm-kubernetes-full/src/main/helm/requirements.yml
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/116
Note that perhaps we should include all the files in the input folder, but for now, I don't want to open this door as it might open a can of worms.
> Additional resources to include Rancher Charts files and requirements

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmChartConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
- docs/modules/ROOT/pages/index.adoc
- integration-tests/helm-kubernetes-full/src/main/helm/Chart.yaml
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
- integration-tests/helm-kubernetes-with-templates/src/main/helm/Chart.yaml
Fix https://github.com/quarkiverse/quarkus-helm/issues/117
> Allow providing a Chart.yml template

- .github/project.yml
- deployment/pom.xml
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- docs/pom.xml
- integration-tests/helm-kubernetes-config/pom.xml
- integration-tests/helm-kubernetes-full/pom.xml
- integration-tests/helm-kubernetes-minimal/pom.xml
- integration-tests/helm-kubernetes-with-dependency/pom.xml
- integration-tests/helm-kubernetes-with-dependency/src/main/resources/application.properties
- integration-tests/helm-kubernetes-with-templates/pom.xml
- integration-tests/helm-openshift-minimal/pom.xml
- integration-tests/pom.xml
- pom.xml
- runtime/pom.xml
Fix https://github.com/quarkiverse/quarkus-helm/issues/126
> Disable Helm Writer session from Dekorate always

- .github/workflows/build.yml
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmDependencyConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/MaintainerConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/ValueReferenceConfig.java
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
- docs/modules/ROOT/pages/index.adoc
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
And the map key should be used if the name is not set.  
Fix https://github.com/quarkiverse/quarkus-helm/issues/130
> The name property in configuration should be optional

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/ValueReferenceConfig.java
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
- integration-tests/helm-kubernetes-with-templates/src/main/resources/application.properties
- integration-tests/helm-kubernetes-with-templates/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesWithTemplatesIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/134
> Support value as map properties

- .github/workflows/build.yml
- deployment/src/main/java/io/quarkiverse/helm/deployment/AddIfStatementConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmChartConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
- docs/modules/ROOT/pages/index.adoc
- integration-tests/helm-kubernetes-with-templates/src/main/resources/application.properties
- integration-tests/helm-kubernetes-with-templates/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesWithTemplatesIT.java
- integration-tests/helm-kubernetes-with-templates/src/test/resources/expected-ingress.yaml
Fix https://github.com/quarkiverse/quarkus-helm/issues/137
> Support if statements at resource level

- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/153
> Use latest decorator that was used instead of the first

- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/154
> Do not camel case properties in the generated Helm manifests

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- integration-tests/helm-kubernetes-with-dependency/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesWithDependencyIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/163
> Dependencies should be enabled by default

- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- integration-tests/helm-kubernetes-full/src/main/helm/Chart.yaml
- integration-tests/helm-kubernetes-with-dependency/src/main/helm/values.yaml
- integration-tests/helm-kubernetes-with-dependency/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesWithDependencyIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/164
> Provided application config from custom values.yaml should take priority

- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/167
> Support configuration with the root alias already set

- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/170
> Fix `profile` property is ignored for values without a path

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmChartConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
- integration-tests/helm-kubernetes-full/src/main/helm/crds/crontabs.stable.example.com.yaml
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/174
> Add crd folder if does exist from helm input directory

- .github/workflows/build.yml
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/190
> Support System.getenv properties when mapping env values

- .github/workflows/build.yml
- README.md
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/example-crud.adoc
- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/index.adoc
- integration-tests/helm-kubernetes-config/src/main/java/io/quarkiverse/helm/tests/kubernetes/Endpoint.java
- integration-tests/helm-kubernetes-full/src/main/java/io/quarkiverse/helm/tests/kubernetes/Endpoint.java
- integration-tests/helm-kubernetes-minimal/src/main/java/io/quarkiverse/helm/tests/kubernetes/Endpoint.java
- integration-tests/helm-kubernetes-with-dependency/src/main/java/io/quarkiverse/helm/tests/kubernetes/Endpoint.java
- integration-tests/helm-kubernetes-with-templates/src/main/java/io/quarkiverse/helm/tests/kubernetes/Endpoint.java
- integration-tests/helm-openshift-minimal/src/main/java/io/quarkiverse/helm/tests/openshift/Endpoint.java
- integration-tests/helm-without-kubernetes/src/main/java/io/quarkiverse/helm/tests/kubernetes/Endpoint.java
- pom.xml
Fix https://github.com/quarkiverse/quarkus-helm/issues/193
> Support Quarkus 3.x

- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/utils/MapUtils.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/201
> Sort the generated values files

- docs/modules/ROOT/pages/index.adoc
Fix https://github.com/quarkiverse/quarkus-helm/issues/203
> Clarify naming convention for system properties

- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/206
> Automatically add the value from the Helm dependency condition

- deployment/src/main/java/io/quarkiverse/helm/deployment/AddIfStatementConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmDependencyConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/ValueReferenceConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/utils/HelmConfigUtils.java
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/209
> Support rootless properties via configuration

- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/utils/ValuesHolder.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/utils/YamlExpressionParserUtils.java
- docs/modules/ROOT/pages/index.adoc
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/207
> Use the configuration from the generated values.yaml in the application.properties

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/208
> Validate properties to not use "-" characters

- README.md
- deployment/src/main/java/io/quarkiverse/helm/deployment/AddIfStatementConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmChartConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/ValueReferenceConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/ValuesSchemaConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/ValuesSchemaPropertyConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/decorators/LowPriorityAddEnvVarDecorator.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/utils/ReadmeBuilder.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/utils/ValuesHolder.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/utils/ValuesSchemaUtils.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/includes/quarkus-helm.adoc
- docs/modules/ROOT/pages/index.adoc
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-with-templates/src/main/resources/application.properties
- pom.xml
- runtime/pom.xml
This pull request brings a lot of new features coming from Dekorate latest release:
- Support the generation of a `README.md` file
- Support the generation of the `values.schema.file`
Fix https://github.com/quarkiverse/quarkus-helm/issues/214
> Bump Quarkus to 3.0.0.CR1

- README.md
- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- docs/modules/ROOT/pages/index.adoc
Fix https://github.com/quarkiverse/quarkus-helm/issues/227
> Fix support of only one on-resource-kind and on-resource-name

- .github/workflows/build.yml
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmChartConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmDependencyConfig.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/decorators/LowPriorityAddEnvVarDecorator.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/utils/HelmConfigUtils.java
- integration-tests/helm-kubernetes-with-dependency/src/main/resources/application.properties
Fix https://github.com/quarkiverse/quarkus-helm/issues/226
> Align properties `wait-for-service` and `condition` in Helm dependencies

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Fix https://github.com/quarkiverse/quarkus-helm/issues/229
> Skip mapping of properties that are already defined in app properties

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
Cherrypick of https://github.com/quarkiverse/quarkus-helm/pull/232
Fix https://github.com/quarkiverse/quarkus-helm/issues/237
> [2.16] Skip mapping of properties that are already defined in app properties

- docs/modules/ROOT/pages/index.adoc
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
Related to https://github.com/quarkiverse/quarkus-helm/pull/246
> Update documentation to explain the property values-profile-separator

- .github/workflows/build.yml
- deployment/src/main/java/io/quarkiverse/helm/deployment/QuarkusHelmWriterSessionListener.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/utils/YamlExpressionParserUtils.java
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/example-config.adoc
- docs/modules/ROOT/pages/example-crud.adoc
- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/index.adoc
- integration-tests/helm-kubernetes-config/src/main/docker/Dockerfile.jvm
- integration-tests/helm-kubernetes-config/src/main/java/io/quarkiverse/helm/tests/kubernetes/Endpoint.java
- integration-tests/helm-kubernetes-config/src/main/kubernetes/kubernetes.yml
- integration-tests/helm-kubernetes-config/src/main/resources/application.properties
fix https://github.com/quarkiverse/quarkus-helm/issues/261
> Document how to map properties using Quarkus K8s Config extension

- .github/project.yml
> Request release 1.2.0

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/rules/ConfigReferenceStrategy.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/rules/ConfigReferenceStrategyManager.java
- deployment/src/main/java/io/quarkiverse/helm/deployment/rules/HttpGetPortConfigReferenceStrategy.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- integration-tests/helm-kubernetes-full/src/main/resources/application.properties
- integration-tests/helm-kubernetes-full/src/test/java/io/quarkiverse/helm/tests/kubernetes/KubernetesFullIT.java
- integration-tests/helm-kubernetes-full/src/test/resources/expected-readinessProbe.yaml
- integration-tests/helm-kubernetes-full/src/test/resources/expected-startupProbe.yaml
- pom.xml
Fix https://github.com/quarkiverse/quarkus-helm/issues/295
> Fix resolution of ports in the generated templates

- deployment/pom.xml
- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- pom.xml
- spi/pom.xml
- spi/src/main/java/io/quarkiverse/helm/spi/CustomHelmOutputDirBuildItem.java
The pull request introduces an spi and new build item that allows controlling the output directory of helm.
> Allow controlling the output dir from other extensions

- deployment/src/main/java/io/quarkiverse/helm/deployment/HelmProcessor.java
- deployment/src/main/resources/build-time-list
- docs/modules/ROOT/pages/includes/attributes.adoc
Related to https://github.com/quarkiverse/quarkus-helm/issues/335
> Do not map properties that are Quarkus build-time configuration

- runtime/src/main/resources/META-INF/quarkus-extension.yaml
Fix https://github.com/quarkiverse/quarkus-helm/issues/381
> Add helm logo to the extension descriptor

- .github/project.yml
fix https://github.com/quarkiverse/quarkus-helm/issues/402
> Request for release 1.2.7
